server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_supermarket?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update

